name: Build Publish and Deploy
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["14"]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
      - run: |
          npm install
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.TOKEN}}
          workflow: build-and-publish.yml
          workflow_conclusion: success
          repo: shashank-indukuri/todo
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "to-do-mern-stack" #Must be unique in Heroku
          heroku_email: "shashank.indukuri05@gmail.com"
          appdir: /
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: .
